/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example




//etapa 1
fun main() {
    val a = 2
    val b = 5
    val c = -3

    if (a == 0) {
        println("El coeficiente 'a' no puede ser cero en una función cuadrática.")
        return
    }

    val funcion = buildString {
        append("${a}x²")
        if (b != 0) {
            append(if (b > 0) " + ${b}x" else " - ${-b}x")
        }
        if (c != 0) {
            append(if (c > 0) " + $c" else " - ${-c}")
        }
    }

    println("La función cuadrática es: $funcion")
}

